export const MENU = {
  PURCHASE_PRICE: 'PP',
  USER: 'USER',
  ROLE: 'ROLE',
  PURCHASE_REQUEST: 'PR',
  VENDOR: 'VENDOR',
  PURCHASE_ORDER: 'PO',
  GOODS_PO_RECEIPT: 'GPOR',
  GOODS_TRANSFER: 'GT',
  ORDER: 'ORDER',
  ITEM: 'ITEM',
  USER_PRICE: 'USER_PRICE',
};
